import { TanstackQueryProvider } from "@/tanstack-query/TanstackQueryProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SWRProvider from "@/swr/SWRProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SWRProvider>
        <body className={inter.className}>{children}</body>
      </SWRProvider>
    </html>
  );
  // return (
  //   <html lang="en">
  //     <TanstackQueryProvider>
  //       <body className={inter.className}>{children}</body>
  //     </TanstackQueryProvider>
  //   </html>
  // );
}
